{
 "title": "Job Market Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Nombre d'offres actives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_active_offers\nFROM job_offers\nWHERE status = 'active';"
    }
   ]
  },
  {
   "title": "Entreprises qui recrutent",
   "type": "stat",
   "description": "Nombre total des entreprises avec des offres actives",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT c.company_id) AS total_active_companies\nFROM companies c\nJOIN job_offers jo ON c.company_id = jo.company_id\nWHERE jo.status = 'active';"
    }
   ]
  },
  {
   "title": "Évolutions des offres actives dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE(created_at) AS date,\n  COUNT(*) AS total_active_offers\nFROM job_offers\nWHERE status = 'active'\nGROUP BY DATE(created_at)\nORDER BY date ASC;\n"
    }
   ]
  },
  {
   "title": "Proportion des offres par source",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  s.name AS source_name,\n  COUNT(*) AS offer_count\nFROM job_offers jo\nJOIN sources s ON jo.source_id = s.source_id\nwhere status = 'active'\nGROUP BY s.name\nORDER BY offer_count DESC;"
    }
   ]
  },
  {
   "title": "Distribution des offres par localisation",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  l.location AS location_name,\n  l.latitude,\n  l.longitude,\n  COUNT(*) AS total_offers\nFROM job_offers jo\nJOIN locations l ON jo.location_id = l.location_id\nGROUP BY l.location, l.latitude, l.longitude\nHAVING l.latitude IS NOT NULL AND l.longitude IS NOT NULL;"
    }
   ]
  },
  {
   "title": "Top 10 des entreprises qui recrutent en France",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  c.name AS company_name,\n  COUNT(*) AS offer_count\nFROM job_offers jo\nJOIN companies c ON jo.company_id = c.company_id\nWHERE \n  jo.status = 'active'\n  AND c.name IS NOT NULL\n  AND TRIM(c.name) <> ''\nGROUP BY c.name\nORDER BY offer_count DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Top 10 des entreprises recrutant dans la Tech",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \n  c.name AS company_name,\n  COUNT(*) AS offer_count\nFROM job_offers jo\nJOIN companies c ON jo.company_id = c.company_id\nJOIN (\n    SELECT job_id, title FROM adzuna_offers\n    UNION ALL\n    SELECT job_id, title FROM france_travail_offers\n    UNION ALL\n    SELECT job_id, title FROM jsearch_offers\n) AS offers ON jo.job_id = offers.job_id\nWHERE \n  jo.status = 'active'\n  AND c.name IS NOT NULL\n  AND TRIM(c.name) <> ''\n  AND (\n    offers.title ILIKE '%dev%' OR\n    offers.title ILIKE '%base de données%' OR\n    offers.title ILIKE '%software%' OR\n    offers.title ILIKE '%data%' OR\n    offers.title ILIKE '%digital%' OR\n    offers.title ILIKE '%cyber%' OR\n    offers.title ILIKE '%cloud%' OR\n    offers.title ILIKE '%ingénieur%' OR\n    offers.title ILIKE '%engineer%' OR\n    offers.title ILIKE '%docker%' OR\n    offers.title ILIKE '%aws%' OR\n    offers.title ILIKE '%gcp%'\n  )\n  AND (\n    offers.title NOT ILIKE '%formation%'\n    AND offers.title NOT ILIKE '%certification%'\n    AND offers.title NOT ILIKE '%certifiante%'\n  )\nGROUP BY c.name\nORDER BY offer_count DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Proportion des 10 villes qui recrutent le plus",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE\n    WHEN LOWER(l.location) LIKE 'paris%' \n      OR LOWER(l.location) LIKE 'nanterre%' \n      OR LOWER(l.location) LIKE 'courbevoie%'\n    THEN 'PARIS'\n    ELSE l.location\n  END AS location_name,\n  COUNT(*) AS offer_count\nFROM job_offers jo\nJOIN locations l ON jo.location_id = l.location_id\nWHERE \n  jo.status = 'active'\n  AND l.location IS NOT NULL\n  AND TRIM(l.location) <> ''\nGROUP BY location_name\nORDER BY offer_count DESC\nLIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Top 15 métiers de la tech",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 8, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \n  title,\n  COUNT(*) AS offer_count\nFROM (\n  -- France Travail\n  SELECT france_travail_offers.title\n  FROM france_travail_offers\n  JOIN job_offers ON france_travail_offers.job_id = job_offers.job_id\n  WHERE \n    job_offers.status = 'active'\n    AND france_travail_offers.title IS NOT NULL\n    AND TRIM(france_travail_offers.title) <> ''\n    AND (\n      france_travail_offers.title ILIKE '%data%' OR\n      france_travail_offers.title ILIKE '%cyber%' OR\n      france_travail_offers.title ILIKE '%développeur%' OR\n      france_travail_offers.title ILIKE '%developpeur%' OR\n      france_travail_offers.title ILIKE '%cloud%' OR\n      france_travail_offers.title ILIKE '%ingénieur%' OR\n      france_travail_offers.title ILIKE '%ingenieur%' OR\n      france_travail_offers.title ILIKE '%software%' OR\n      france_travail_offers.title ILIKE '%numérique%' OR\n      france_travail_offers.title ILIKE '%digital%'\n    )\n\n  UNION ALL\n\n  -- Adzuna\n  SELECT adzuna_offers.title\n  FROM adzuna_offers\n  JOIN job_offers ON adzuna_offers.job_id = job_offers.job_id\n  WHERE \n    job_offers.status = 'active'\n    AND adzuna_offers.title IS NOT NULL\n    AND TRIM(adzuna_offers.title) <> ''\n    AND (\n      adzuna_offers.title ILIKE '%data%' OR\n      adzuna_offers.title ILIKE '%cyber%' OR\n      adzuna_offers.title ILIKE '%développeur%' OR\n      adzuna_offers.title ILIKE '%developpeur%' OR\n      adzuna_offers.title ILIKE '%cloud%' OR\n      adzuna_offers.title ILIKE '%ingénieur%' OR\n      adzuna_offers.title ILIKE '%ingenieur%' OR\n      adzuna_offers.title ILIKE '%software%' OR\n      adzuna_offers.title ILIKE '%numérique%' OR\n      adzuna_offers.title ILIKE '%digital%'\n    )\n\n  UNION ALL\n\n  -- JSearch\n  SELECT jsearch_offers.title\n  FROM jsearch_offers\n  JOIN job_offers ON jsearch_offers.job_id = job_offers.job_id\n  WHERE \n    job_offers.status = 'active'\n    AND jsearch_offers.title IS NOT NULL\n    AND TRIM(jsearch_offers.title) <> ''\n    AND (\n      jsearch_offers.title ILIKE '%data%' OR\n      jsearch_offers.title ILIKE '%cyber%' OR\n      jsearch_offers.title ILIKE '%développeur%' OR\n      jsearch_offers.title ILIKE '%developpeur%' OR\n      jsearch_offers.title ILIKE '%cloud%' OR\n      jsearch_offers.title ILIKE '%ingénieur%' OR\n      jsearch_offers.title ILIKE '%ingenieur%' OR\n      jsearch_offers.title ILIKE '%software%' OR \n      jsearch_offers.title ILIKE '%numérique%' OR \n      jsearch_offers.title ILIKE '%digital%' \n    )\n) AS combined_titles\nGROUP BY title\nORDER BY offer_count DESC\nLIMIT 15;"
    }
   ]
  }
 ]
}