FROM python:3.12-slim
LABEL authors="dani"
WORKDIR /app
COPY ./job_market_app/ .
RUN pip install --no-cache-dir streamlit requests
EXPOSE 8501
ENV PYTHONPATH=/app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]