FROM python:3.12-slim
LABEL authors="Dani"
WORKDIR /src
COPY ./requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt
EXPOSE 8000
ENV PYTHONPATH=/src
CMD ["uvicorn", "API.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]